Allow to deploy Lambda inside VPC
hammerstonedev/sidecar pull request #52
Opened 2022-02-13 22:04 UTC by deleugpn

This pull request enhances sidecar abilities to allow developers to deploy sidecar Lambda functions inside a VPC.

2022-02-14 16:51 UTC, datashaman requested changes
Random internet stranger's 2c. :)

2022-02-14 16:51 UTC, datashaman commented on src/LambdaFunction.php
> +        $sg = config('sidecar.vpc.security_group');
The AWS config is `SecurityGroupIds`, it should be plural and an array.

2022-02-14 16:51 UTC, datashaman commented on config/sidecar.php
> +        'security_groups' => env('SIDECAR_VPC_SECURITY_GROUP'),
```suggestion
        'security_groups' => explode(',', env('SIDECAR_VPC_SECURITY_GROUPS', '')),
```

2022-02-14 16:51 UTC, datashaman commented on config/sidecar.php
> +        'subnets' => env('SIDECAR_VPC_SUBNETS'),
```suggestion
        'subnets' => explode(',', env('SIDECAR_VPC_SUBNETS', '')),
```

2022-02-14 16:51 UTC, datashaman commented on src/LambdaFunction.php
> +        $sg = config('sidecar.vpc.security_group');
```suggestion
        $securityGroups = config('sidecar.vpc.security_groups');
```

2022-02-14 16:51 UTC, datashaman commented on src/LambdaFunction.php
> +                'SecurityGroupIds' => Arr::wrap($sg),
```suggestion
                'SecurityGroupIds' => $securityGroups,
```

2022-02-14 18:24 UTC, deleugpn commented
I appreciate the suggested review but I would argue that most use cases will be a single sg and potentially hard-coded subnets instead of environment variables.

The config file just gives an idea how to go about it. Using Arr::wrap gives the flexibility of allowing users set an array or a single string.

2022-02-15 23:53 UTC, aarondfrancis commented
Mmm this is great, thanks for doing this @deleugpn. And thanks for the extra set of eyes @datashaman! 

Let me review the Lambda docs on this and see if I can get it merged this week. I'll get back to ya!

2023-05-09 17:51 UTC, matthewdevine commented
Just wondering if you found any issues regarding the VPC setup by Sidecar?  Having this built-in would help streamline our deployments

2023-07-10 20:21 UTC, lautaroml commented
Any news regarding this?

I use laravel vapor with a private network and can't access the database...

2023-11-08 15:24 UTC, d8vjork commented
I also wonder when this will be merged as my team really needs this feature

2024-08-05 10:53 UTC, flfw commented
Is there any update on when this might be merged please? This would be very useful for our team.

2025-03-13 20:30 UTC, jacob-gardiner commented
@aarondfrancis, is there still a plan to merge this? Unfortunately, this is blocking us from using sidecar.

2025-05-29 13:20 UTC, closed without merging

2026-02-13 14:56 UTC, emaadali commented
@aarondfrancis Any chance this could get merged in? We need Lambdas to be in VPCs/subnets for SOC II compliance.